### ISSUE TITLE
Package n3acv41w hang

### ISSUE THREAD

**Issue by pimpmyname2** [jantari/LSUClient#101]
### Version

1.6.0

### Computer Model

21HM006GMX

### Problem

Parsing dependencies for package n3acv41w hangs and says MCUFWRevCheck.exe has been running for 5+ minutes.
In the log it says OpenDevice fail + Open ISH or SFH driver failed: 13

EDIT:
It skipped after 10 minutes, just wanna give a headsup on it :)

**Comment by jantari** [comment]
Were you able to find the reason for the hang? If you were able to fix it or work around it, please share for others who might run into the same issue.

If it's a fix that could be integrated into LSUClient for everyone we can think about doing that. Otherwise I'd close the issue.

**Comment by pimpmyname2** [comment]
No sorry. Ill close it :)
