### ISSUE TITLE
Get-LSUpdate Error

### ISSUE THREAD

**Issue by Abdulmusawwir** [jantari/LSUClient#105]
### Version

1.6.2

### Computer Model

80TL

### Problem

Get-LSUpdate : The 'Get-LSUpdate' command was found in the module 'LSUClient', but the module could not be 
loaded. For more information, run 'Import-Module LSUClient'.
At line:1 char:1
+ Get-LSUpdate
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-LSUpdate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
<img width="741" alt="ErrorGetUpdate" src="https://github.com/user-attachments/assets/cdb6d1ce-cbfe-49cb-a3d4-0b043965e6f7">

### Additional context

Running via Level RMM

**Comment by jantari** [comment]
The error is not from LSUClient, but very helpful:

> For more information, run 'Import-Module LSUClient'.

Do that.

**Comment by jantari** [comment]
Were you able to find what the issue was and solve it?

**Comment by Abdulmusawwir** [comment]
> Import-Module LSUClient

Thank you! That resovled the problem.
