### ISSUE TITLE
Download Driver but no Install it

### ISSUE THREAD

**Issue by ganech88** [jantari/LSUClient#108]
### Version

1.6

### Computer Model

21HESBKE04

### Problem

LSUClient installs all drivers but i have somo issues that the application downloads a drivers but never get installed

10/4/2024 3:03:23 PM 2 updates found Instalando Actualizacion 1 of 2: USB4(TBT4) DisplayPort Bandwidth Management - 11 (22H2 or Later) PackageInstallResult Instalando Actualizacion 2 of 2: Lenovo MEP Opt-in Driver - 11 (23H2 or Later) PackageInstallResult

10/4/2024 3:28:40 PM 2 updates found Instalando Actualizacion 1 of 2: USB4(TBT4) DisplayPort Bandwidth Management - 11 (22H2 or Later) PackageInstallResult Instalando Actualizacion 2 of 2: Lenovo MEP Opt-in Driver - 11 (23H2 or Later) PackageInstallResult 

Other Drivers Installs successefuly, but i have random cases with this.

**Comment by jantari** [comment]
What does the PackageInstallResult value look like for these?

**Comment by jantari** [comment]
The PackageInstallResult will tell you whether the install was successful or not. That's the first step to troubleshooting this. Please reproduce the issue and capture the full PackageInstallResult objects from `Install-LSUpdate`.

**Comment by jantari** [comment]
Closing due to no response.
