### ISSUE TITLE
Download drivers for a targeted model

### ISSUE THREAD

**Issue by randrini** [jantari/LSUClient#13]
Being able to download drivers for a different model, not your own computer.
For example, I would like to download T460 drivers on my personal computer so I could use them later.

**Comment by jantari** [comment]
Does:

```powershell
Get-LSUpdate -Model 20FM -All | Save-LSUpdate -Path "C:\t460drivers"
```

cover your usecase?

**Comment by jantari** [comment]
Hey, the command I showed you does what you asked and you didn't reply in a while so I'm closing this issue as solved now.

**Comment by randrini** [comment]
Yes it works! Sorry I was so busy I always forgot! Thanks man!

**Comment by jantari** [comment]
No problem, happens to me too :)
