### ISSUE TITLE
Issue with the extract command (Powershell 5, Windows 10 lenovo laptop)

### ISSUE THREAD

**Issue by Powershellder** [jantari/LSUClient#16]
An error occurs during the execution of the script:

`$updates = Get-LSUpdate
$updates | Save-LSUpdate -ShowProgress
$updates | Install-LSUpdate -Verbose
Invoke-PackageCommand : Cannot validate argument on parameter 'Command'. The argument is null or empty. Provide an argument that is not null or empty, 
and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.1.0\private\Expand-LSUpdate.ps1:11 char:73
+ ... Invoke-PackageCommand -Path $Path -Command $Package.Extracter.Command
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-PackageCommand], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-PackageCommand
 
WARNING: Extraction of package djcn15ww may have failed!`

Device info:
Manufacturer: LENOVO
Model: 20SM
Operating System: Microsoft Windows 10 Pro 10.0.18363

Module version used: 1.1.0

**Comment by jantari** [comment]
I actually fixed this a while ago in a222ade, but it didn't make it in time for v1.1.0.

I'll work on releasing a v1.1.1 today that includes this fix as well as #15.

Thanks for reporting!

**Comment by jantari** [comment]
[v1.1.1](https://www.powershellgallery.com/packages/LSUClient/1.1.1) is released 🚀
