### ISSUE TITLE
PID_5003 error

### ISSUE THREAD

**Issue by jgriffiths014** [jantari/LSUClient#2]
upon running the example cmd, Get-LSUpdate throws an error, PID_5003 is not recognised as an internal or external command.

Also after that it also throws 'The Variable $ITEM cannot be retrieved because it has not been set'

Laptop is Lenovo T460s running Win10 Ent 1903.

**Comment by jantari** [comment]
Thanks for the issue report, this is fixed in Version 1.0.1 which I just published!
