### ISSUE TITLE
Install-LSUpdate Run Against Path

### ISSUE THREAD

**Issue by danielolinger** [jantari/LSUClient#20]
**Describe the solution you'd like**
Point Install-LSUpdate at a path with the patches, without requiring Get-LSUpdate be run first

**Describe alternatives you've considered**
N/A

**Additional context**
I have built a solution using LSUClient to download drivers for models found in my SCCM database as well as ad-hoc by providing the 4-char product ID. Then I distribute out to cache points across the remote locations to be used for OS deployments and updating our machines. I run this on a weekly schedule. When using Get-LSUpdate and piping the results to Install-LSUpdate, it could potentially have new updates that Lenovo has added since my last weekly run. Does this cause any issue with the install process if a package's folder/files are not available?

I didn't dig into your code to see what is referenced during the pipping. I tried passing the folder name as a foreach, hoping for that to work but it did not.

Thank you for the time and effort on this module. And for releasing it. It has made piloting Lenovo devices much easier for me.

**Comment by jantari** [comment]
Hi, to make sure I understand your process could you describe the solution you've built in more detail?

It sounds to me like you're using something like `Get-LSUpdate -Model 20Q5 -All | Save-LSUpdate -Path \\myserver\Drivers$\20Q5\` to download drivers for different models, and then a command like `Get-LSUpdate | Install-LSUpdate -Path \\myserver\Drivers$\20Q5` to install them on the individual machines? Is that correct?

**Comment by danielolinger** [comment]
Sorry, I will add more details.

First I grab drivers per model with `$Updates = Get-LSUpdate -Model $ModelNumber -All | Where-Object { $_.Category -notmatch 'Software' -and $_.RebootType -eq '3'} | Save-LSUpdate -Path $Path`. These files get saved to a network path. I then have 200+ offices with caching points that I then copy these files to. When we image a machine or update drivers, I'd like to be able to call the already downloaded drivers/EXE setups on my cache point instead of having to reach out to the internet to install the files. Something like `Install-LSUpdate -Path \\Server\lenovo\21UB` and have it scour the path for installers, extract and then continue on installing.

To get it to work, I run the line below. What I noticed was that it still downloaded files to TEMP, but seemed to still reference files in my "Path". The only reason I know this is because a couple of thje drivers I downloaded and distributed out to my offices were 0-bytes and caused an error during installation. Once I updated that file, the error went away. 

`$LSUpdates = Get-LSUpdate -All | Where-Object {$_.Category -notmatch 'Software' -and $_.RebootType -eq '3'}
$LSUpdates | Install-LSUpdate -Path 'C:\ITTools\Drivers\Repository' -SaveBIOSUpdateInfoToRegistry`

**Comment by jantari** [comment]
Ok in that case the files being downloaded to TEMP are used during the system analysis phase, where the module checks which of the available drivers are needed on the computer. Currently these files always come from Lenovo and I haven't built a way to cache them yet.

About your question:

> it could potentially have new updates that Lenovo has added since my last weekly run. Does this cause any issue with the install process if a package's folder/files are not available?

Get-LSUpdate on the client will always reach out to Lenovo to get a list of drivers and then check the `-Path` to see if they're already downloaded - I originally did this just so you can run it multiple times in a row without re-downloading the same packages every time. This means that, if a driver is not found in your caching point it will just download it from Lenovo instead, and try to save it to the `-Path` (caching server in your case). If the user account you run the script as does not have write permissions to that server though, the download will fail and the driver will not be installed/skipped. If this happens it would be visible in the output of `Install-LSUpdate`.

There is also a very slim chance that Lenovo drastically changes the way a driver is installed or detected from one version to the next without changing the package ID. In this unlikely case you might get an install failure.

Both of these problems would be solved by #17 aka. me implementing proper offline driver repository support which I haven't started working on yet. If this is what you need though you should also consider using [Lenovo Update Retriever](https://support.lenovo.com/us/en/solutions/ht037099/#ur) together with Lenovo ThinInstaller, as they're designed for exactly this purpose. However, these tools aren't PowerShell based and not as nice to script around.

**Comment by danielolinger** [comment]
I specifically wanted to avoid the Lenovo tools for that reason and your tool has saved me a bit of work.

Your first comment about the system analysis phase explains the files I saw writing and deleting. If that is so, then everything is already working as I wish.

If the process cannot save a missing package (due to access), is that a terminating error? Does it just write to console and move on?

**Comment by jantari** [comment]
It's not a terminating error, so it will move on with the other packages.

The temp files being downloaded and run even though you don't need the information of whether the packages apply to your _current_ system or not is actually being tracked by #21 now.

We should be able to figure that one out, I agree that it's a bit unnecessary in a use case like yours.

I'm closing this because you can keep using the module like this for now and the remaining issues are covered by #17 and #21 I think
