### ISSUE TITLE
Where {} filtering not matching with Properties

### ISSUE THREAD

**Issue by grandslamjmh** [jantari/LSUClient#28]
**Describe the bug**
Testing a where statement against IsApplicable and IsInstalled. Marking one as True and the other as False. Return results are only showing a table of both == True.

**Error messages or Screenshots**
If applicable, copy and paste error messages or screenshot them to help explain the problem.
```
Get-LSUpdate -all | where {$_.IsApplicable -eq 'True' -and $_.IsInstalled -eq 'False'} | Select Title, Category, Version, Severity, IsApplicable, IsInstalled | FT -AutoSize

Title                                                                     Category                Version           Severity IsApplicable IsInstalled
-----                                                                     --------                -------           -------- ------------ -----------
Intel AMT Driver - 10 [64]                                                Chipset                 1952.14.0.1470 Recommended         True        True
Intel BlueTooth Driver - 10 [64]                                          Bluetooth and Modem     21.80.0.3      Recommended         True        True
Application Interface Driver (Windows 10 Version 1809 or Later) - 10 [64] Software and Utilities  1.0.0.11       Recommended         True        True
Intel Lan driver - 10 [64]                                                Networking LAN Ethernet 12.18.9.23     Recommended         True        True
Intel Wifi Driver - 10 [64]                                               Networking Wireless LAN 21.120.0.9     Recommended         True        True
```

**Please complete the following information:**
 - Computer model: (Run `(gcim CIM_ComputerSystem).Model` to obtain)
 - Module version used:
Model: 10MUS18K00
Module Version: 1.1.3 (PowerShell Gallery)

**Additional context**
Add anything else about the problem here.

Maybe I am treating it as a String of True/False and not using bool as IsApplicable:$True
```
Get-LSUpdate -all | where {$_.IsApplicable -AND -NOT $_.IsInstalled } | Select Title, Category, Version, Severity, IsApplicable, IsInstalled | FT -AutoSize
```
```
Get-LSUpdate -all | where {$_.IsApplicable -eq $true -and $_.IsInstalled -eq $false} | Select Title, Category, Version, Severity, IsApplicable, IsInstalled | FT -AutoSize
```

**Comment by jantari** [comment]
Your own suspicion was exactly right, `IsInstalled` and `IsApplicable` are booleans, so if you compare them for equality with something, it should be with another boolean and not a string.

You can see the types of the properties with `Get-LSUpdate -All | Get-Member` to confirm this.

The two last examples you added should both work as expected.
