### ISSUE TITLE
PowerShell window closes during `Get-LSUpdate`

### ISSUE THREAD

**Issue by jantari** [jantari/LSUClient#34]
**Describe the bug**
Originall reported by @osxdude as part of #33 

**Please complete the following information:**
 - Computer model: 20N4

**Comment by LordMessi** [comment]
Same problem here. Lenovo ThinkPad X280 - Model 20KF

**Comment by jantari** [comment]
I've fixed this in Version 1.3.1 which I'll push to the PowerShell Gallery shortly.

All external commands are now run through an out-of-process powershell runspace which provides sufficient isolation between the powershell process running LSUClient and the `tbtesdkfw_1015_version.exe` program to prevent this annoyance.
