### ISSUE TITLE
Any plan to check if an update has already been applied?

### ISSUE THREAD

**Issue by cblaise504** [jantari/LSUClient#4]
Hey there!  Thanks for sharing this module!  We are checking it out to see if we can fit it in our automated pipeline.

Do you have any plans to add some sort of audit that shows which updates have already been applied?

**Comment by jantari** [comment]
This would be possible.

The way I would probably implement this functionality is when you run `Get-LSUpdate`,
a new boolean property on the objects, let's say `.IsInstalled` would be true of false.
Running `Get-LSUpdate` without `-All` would only return needed (aka applicable and not yet installed)
packages and `Get-LSUpdate -All` would return, well, all of them.

So not exactly a seperate "audit mode", but you could very easily find out which packages
are installed by checking the output of `Get-LSUpdate -All` and the `.IsApplicable` and `.IsInstalled` properties.

However, it would take quite a bit of work and time to implement this feature and it will add a considerable amount of code too - so for now I want to focus on what I consider the core features (finding and installing updates) working as fast, neatly and reliably as possible before I think about what I consider to be "B" priority or convenience features.

For example, I am working on Version 1.0.2 right now which will (so far) add the following:

- Webproxy with authentication support
- No more cmd windows pop up when running locally
- Support for silent ThinkCentre and ThinkStation BIOS updates (currently it can only do ThinkPads silently, oops)

I hope you understand, while this is possible it is a lot of work compared to a relatively small benefit when there are still some things left to do that are less work and yield a bigger benefit - at least in my opinion. So I'm not saying "no", I'm saying "don't expect it this year".

**Comment by cblaise504** [comment]
Understood, and not a problem.

**Comment by jantari** [comment]
Version 1.0.3 of the module is out and brings a new and improved XML-parser that adds support for the `_Driver` requirement spec which is commonly used by Lenovo to detect an installed package as well.

Once `_FileVersion` and `_RegistryKeyValue` are also supported this feature isn't far off anymore.

**Comment by jantari** [comment]
Wanted to let you know that this feature is in the [develop](https://github.com/jantari/LSUClient/tree/develop) branch right now, and if you want you can clone that and give it a try.

**Comment by jantari** [comment]
I merged develop into master and released [v1.1.0](https://github.com/jantari/LSUClient/releases/tag/v1.1.0) officially, so this is now fixed in a stable release.
