### ISSUE TITLE
Add -PresentOnly switch to Get-PnPDevice in Get-LSUpdate.ps1

### ISSUE THREAD

**Issue by WoodneyUK** [jantari/LSUClient#43]
### Version

1.3.2

### Computer Model

20KK

### Problem

I've found that devices are showing drivers are required because the script is returning all drivers (even one's not currently active on the system).  
Fix is to add the -presentonly switch to get-pnpdevice on line 111.

Before:
PS C:\Users\szwoodwa> $script:cachedhardwaretable._PnPID.count
767

After:
PS C:\Users\szwoodwa> $script:cachedhardwaretable._PnPID.count
285

On a few devices, it was matching the hardwareid of drivers that are not present, and marking the driver as required.
In this log, there are 4 hardwareID's found, when only 2 are actually present.

DEBUG: Found 'n25a124w_2_.xml' by its absolute path
DEBUG: Testing and getting basic information on package path 'n25a124w.exe'
DEBUG: Testing and getting basic information on package path 'n25a124w.txt'
DEBUG: Testing and getting basic information on package path 'getw10ver8.exe'
DEBUG: Found 'getw10ver8.exe' by its absolute path
DEBUG: - |> Node: DetectInstall
DEBUG: - - |> Node: _Driver
DEBUG: - - Matched device 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259&REV_1000' with required 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Matched device 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259' with required 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Matched device 'HDAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259&REV_1000' with required 'HDAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Matched device 'HDAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259' with required 'HDAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Trying to match driver based on Date
DEBUG: - - [Got: 05/09/2020 00:00:00, Expected: 07/14/2020 00:00:00]
DEBUG: - - Failed DriverDate test
DEBUG: - - Trying to match driver based on Version
DEBUG: - - [Got: 10.0.19041.264, Expected: 6.0.8988.1^]
DEBUG: - - < Returning 0 from node _Driver
DEBUG: - Tree was OR: Results: 0
DEBUG: - < Returning 0 from node DetectInstall
DEBUG: - |> Node: Dependencies
DEBUG: - - |> Node: And
DEBUG: - - - |> Node: Or
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 1 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 1 from node _PnPID
DEBUG: - - - Tree was OR: Results: 0 1 0 1
DEBUG: - - - < Returning 1 from node Or
DEBUG: - - - |> Node: _OS
DEBUG: - - - < Returning 1 from node _OS
DEBUG: - - - |> Node: _CPUAddressWidth
DEBUG: - - - [ Got: 64, Expected: 64 ]
DEBUG: - - - < Returning 1 from node _CPUAddressWidth
DEBUG: - - - |> Node: _Bios
DEBUG: - - - [ Got: N25ET54W (1.40 ) ]
DEBUG: - - - < Returning 1 from node _Bios
DEBUG: - - - |> Node: Not
DEBUG: - - - Switched state to: DO_NOT_HAVE
DEBUG: - - - - |> Node: _ExternalDetection
DEBUG: - - - - [ Got ExitCode: 9, Expected: 0,1,2 ]
DEBUG: - - - - < Returning 0 from node _ExternalDetection
DEBUG: - - - Tree was OR: Results: 0
DEBUG: - - - < Returning 1 from node Not
DEBUG: - - Tree was AND: Results: 1 1 1 1 1
DEBUG: - - < Returning 1 from node And
DEBUG: - Tree was OR: Results: 1
DEBUG: - < Returning 1 from node Dependencies

Result after adding the switch:

DEBUG: Found 'n25a124w_2_.xml' by its absolute path
DEBUG: Testing and getting basic information on package path 'n25a124w.exe'
DEBUG: Testing and getting basic information on package path 'n25a124w.txt'
DEBUG: Testing and getting basic information on package path 'getw10ver8.exe'
DEBUG: Found 'getw10ver8.exe' by its absolute path
DEBUG: - |> Node: DetectInstall
DEBUG: - - |> Node: _Driver
DEBUG: - - Matched device 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259&REV_1000' with required 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Matched device 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259' with required 'INTELAUDIO\FUNC_01&VEN_10EC&DEV_0285&SUBSYS_17AA2259'
DEBUG: - - Trying to match driver based on Date
DEBUG: - - [Got: 07/14/2020 00:00:00, Expected: 07/14/2020 00:00:00]
DEBUG: - - Passed DriverDate test
DEBUG: - - Trying to match driver based on Version
DEBUG: - - [Got: 6.0.8988.1, Expected: 6.0.8988.1^]
DEBUG: - - < Returning 1 from node _Driver
DEBUG: - Tree was OR: Results: 1
DEBUG: - < Returning 1 from node DetectInstall
DEBUG: - |> Node: Dependencies
DEBUG: - - |> Node: And
DEBUG: - - - |> Node: Or
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 1 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - Tree was OR: Results: 0 1 0 0
DEBUG: - - - < Returning 1 from node Or
DEBUG: - - - |> Node: _OS
DEBUG: - - - < Returning 1 from node _OS
DEBUG: - - - |> Node: _CPUAddressWidth
DEBUG: - - - [ Got: 64, Expected: 64 ]
DEBUG: - - - < Returning 1 from node _CPUAddressWidth
DEBUG: - - - |> Node: _Bios
DEBUG: - - - [ Got: N25ET54W (1.40 ) ]
DEBUG: - - - < Returning 1 from node _Bios
DEBUG: - - - |> Node: Not
DEBUG: - - - Switched state to: DO_NOT_HAVE
DEBUG: - - - - |> Node: _ExternalDetection
DEBUG: - - - - [ Got ExitCode: 9, Expected: 0,1,2 ]
DEBUG: - - - - < Returning 0 from node _ExternalDetection
DEBUG: - - - Tree was OR: Results: 0
DEBUG: - - - < Returning 1 from node Not
DEBUG: - - Tree was AND: Results: 1 1 1 1 1
DEBUG: - - < Returning 1 from node And
DEBUG: - Tree was OR: Results: 1
DEBUG: - < Returning 1 from node Dependencies

**Comment by jantari** [comment]
Have you compared the results with the official System Update tool? Does it show that same driver as available/needed?

I try to emulate the behavior of System Update when it comes to these things, at least by default.

**Comment by WoodneyUK** [comment]
Hi Jantari,
yes i've compared with official tool it shows not required.
Also, when i check in device manager etc, the driver n25a124w is correctly installed.

Also, just wanted to say - you've done a really awesome job with these scripts.  They're making thing much easier for us. Thank you!  
I've got a scheduled task which uses get-lsupdate to download and cache new drivers in the background.  It then stamps a registry key if/when a new driver is ready to be installed.  This regkey is checked by an SCCM application which uses the PSAppdeploytoolkit to interface with the user and close apps etc.

**Comment by jantari** [comment]
Thanks for the kind words! Sounds like you've created quite a cool solution, exactly the kind of flexibility and integrations I had hoped LSUClient would enable for people.

As far as the device situation, I remember running into that before too so I went through some of my notes and found it indeed. It's not always easy getting a machine in this exact state (multiple devices matching, some of them disconnected) to test and verify that situation more extensively but it's something I'll look into.

The thing is I sometimes find it very useful to be able to find and install driver updates for a docking station for example, even if that docking station is not connected in this exact moment. Maybe the computer will be docked an hour later or the next day and can then benefit from the pre-updated driver.

So I think I'd make this a parameter on `Get-LSUpdate`. Perhaps something like `-IncludePhantomDevices` or `-IncludeDisconnectedDevices`.

**Comment by jantari** [comment]
I addressed this in Version 1.3.4. Thanks for the issue report.

Disconnected / non-present devices are now ignored by default as you suggested, to bring the behavior and results in line with System Update. However one can choose to continue to include non-present devices like before with the new `-IncludePhantomDevices` parameter.
