### ISSUE TITLE
update says success but update never gets installed

### ISSUE THREAD

**Issue by sgtwtf** [jantari/LSUClient#44]
### Version

1.3.4

### Computer Model

10VT000JUS

### Problem

Trying to automate the BIOS update process as part of a new build using my RMM. 
Running `Get-LSUpdate | Where-Object { $_.Installer.Unattended } | Install-LSUpdate -SaveBIOSUpdateInfoToRegistry` I get a message "BIOS UPDATE SUCCESS: An immediate full SHUTDOWN is strongly recommended to allow the BIOS update to complete!" 
I shut down the system and the first time I waited 5 min for it to come back up and tried again and waited 16 min and still never turns back on and when I manually power up and run `Get-LSUpdate | Where-Object { $_.Installer.Unattended }` I see the same update listed. 
ID                   Title                                                                         Category  Version Severity            IsApplicable
--                  -----                                                                          --------      ------- --------             ------------
m25jy5fusa Flash BIOS Update for ThinkCentre M725s - 10 [64] BIOS UEFI 0.0.0.0 Recommended True

Also the Version number is blank "0.0.0.0"

### Additional context

![2021-12-08_11h46_01](https://user-images.githubusercontent.com/7502836/145274128-c7932317-ea33-4aa8-934d-d3cca44d8b42.png)
![2021-12-08_11h46_22](https://user-images.githubusercontent.com/7502836/145274130-89ae6a14-2ce8-4848-8df5-1fbbed49c5bb.png)

**Comment by jantari** [comment]
It's possible you weren't performing a full shutdown but rather a hybrid shutdown which is more like hibernation and what Windows 8 and newer call the "fast startup" feature.

Try shutting down with the `shutdown /s /t 1 /f` command after installing the BIOS update, rather than shutting down through the buttons in the start menu for example which won't actually perform a full poweroff by default.

**Comment by sgtwtf** [comment]
that did the trick...TY

**Comment by jantari** [comment]
No problem, the fast startup feature can cause some unexpected behavior. You can also disable it entirely if you want so all shutdowns are "real" shutdowns again.
