### ISSUE TITLE
Can -NoNewWindow be changed to -WindowStyle Hidden

### ISSUE THREAD

**Issue by ChrisKibble** [jantari/LSUClient#5]
Because you're calling CMD.EXE which is then calling the actual detecting executable, there are a number of command window popups.  This would only happen when running locally, so not a huge inconvenience, but seems to be solved by just swapping out the -NoNewWindow parameter for -WindowStyle Hidden.

`$externalDetection = Start-Process -FilePath cmd.exe -WorkingDirectory "$env:Temp" -ArgumentList '/C', "$extCommand >nul" -PassThru -Wait -WindowStyle Hidden`

**Comment by jantari** [comment]
Hi, thanks for the report.

This is already addressed in the next version (1.0.2) with an entirely new and more robust function for running all external executables.

Version 1.0.2 is feature-complete but I want to test it a bit more before I release it to the PowerShell Gallery.

Although I could upload it to GitHub first so you can test and provide feedback on it - I'll be at my computer again in roughly 24h then I'll push 1.0.2 to github and notify you!

**Comment by jantari** [comment]
I pushed all my commits to GitHub, so the work-in-progress 1.0.2 version of the module is now available here

This issue was fixed by commits c4f5220298e6ba29231e4e0eebc84afc5baab468 and d32c84c89940ca5e0d3c47b4397e82cb36665393 so please feel free to give it a try now
