### ISSUE TITLE
error with Get-LSUpdate

### ISSUE THREAD

**Issue by bios-john** [jantari/LSUClient#51]
### Version

current master

### Computer Model

20FW003NGE

### Problem

Dear jantari,

thanks for your contribution on making our lives easier!

I tried using your script but unfortunately I have problems running it.
The installation works fine but on the first run of Get-LSUpdate the powershell windows closes.
After that i receive the error message (see additional content, sorry it is in German)
Basicly it is saying the file "C:\Program
Files\WindowsPowerShell\Modules\LSUClient\1.4.1\LSUClient.Format.ps1xml" cannot be found.
I checked that out and it was missing. So I complete removed the module from my computer and installied it again.
The same procedure (including errors) happened and I was able to recognize, that the missing file was there until the first run of  Get-LSUpdate. 
Somehow it has been removed. Is there any special permissions for that folder needed?
Also I tried the same on another Lenovo device with the same results.

Thanks in advance for your help.

### Additional context

Import-Module : Das Element "FormatsToProcess" im Modulmanifest ist ungültig: Der Pfad "C:\Program
Files\WindowsPowerShell\Modules\LSUClient\1.4.1\LSUClient.Format.ps1xml" kann nicht gefunden werden, da er nicht
vorhanden ist.. Stellen Sie sicher, dass für dieses Feld in der Datei "C:\Program
Files\WindowsPowerShell\Modules\LSUClient\1.4.1\LSUClient.psd1" ein gültiger Wert angegeben ist.
In Zeile:1 Zeichen:1
+ Import-Module LSUClient
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...\LSUClient.psd1:String) [Import-Module], Argumen
   tException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by jantari** [comment]
Hi and thank you for submitting an issue to make the module better :)

The fact that the file is being deleted *as* PowerShell tries to load/process it makes me think the file may be noticed and blocked/removed on-access by security software such as antivirus, corporate policies etc.? If you could check through the logs of any installed security products, maybe you'll find what's deleting the file.

If you can't find it in there you may have to monitor the computers processes for file deletion events as you try to run `Get-LSUpdate` (or `Import-Module LSUClient`) - you can do that for example with "Process Monitor" or "Sysmon" from Microsoft.

**Comment by jantari** [comment]
Have you been able to find out how the file was being deleted?

**Comment by bios-john** [comment]
hey @jantari and sorry for the delay on my reply.
You are right... my antivirus (Bitdefender) blocked it with the reason: AT4.Detection which in most cases is false positive.
I guess this issue can be closed and marked as solved.
Thanks for your hint!!
