### ISSUE TITLE
offline repository, no internet on clients

### ISSUE THREAD

**Issue by horst420** [jantari/LSUClient#53]
### Version

1.4.1

### Question

Hi Jantari,

thanks for your great work.

i am running into following problem.

I want to use an offline repository, copied by software deployment tool.
There is no  internet connection on the clients, is this possible?

Get-LSUpdate -Model 10MR -All | Save-LSUpdate -Path 'C:\10MR_Drivers' -ShowProgress

but if i run Get-LSUpdate or Install-LSUpdate. the Tool is searching for database.xml or 10MR_Win10.xml which are not in the local directory. (if i put the database.xml from lenovo to the repository, the driver packages are trying to download again from lenovo).

> $updates=Get-LSUpdate -Repository 'C:\10MR_Drivers\' -Verbose -Debug

AUSFÜHRLICH: Adjusting the DebugPreference to 'Continue'.
AUSFÜHRLICH: Lenovo Model is: 10MR
DEBUG: Resolving file path 'C:\10MR_Drivers\'
AUSFÜHRLICH: Created temporary scratch directory: C:\Users\su-mr-admin\AppData\Local\Temp\ruz1ibys.w2l
AUSFÜHRLICH: Looking for packages in repository 'C:\10MR_Drivers\' (Type: FILE)
DEBUG: Resolving file path 'C:\10MR_Drivers\10MR_Win10.xml'
DEBUG: Resolving file path 'C:\10MR_Drivers\database.xml'
WARNUNG: The repository 'C:\10MR_Drivers\' did not contain either a '10MR_Win10.xml' or 'database.xml' file to get
packages from
No packages for computer model '10MR' could be retrieved from repository 'C:\10MR_Drivers\'
In C:\Program Files\WindowsPowerShell\Modules\LSUClient\public\Get-LSUpdate.ps1:149 Zeichen:13
+             throw "No packages for computer model '${Model}' could be ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No packages for...\10MR_Drivers\':String) [], RuntimeException
    + FullyQualifiedErrorId : No packages for computer model '10MR' could be retrieved from repository 'C:\10MR_Driver
   s\'

PS> $Error | select * | Format-List *

PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: No packages for computer model '10MR' could be
                        retrieved from repository 'C:\10MR_Drivers\'
TargetObject          : No packages for computer model '10MR' could be retrieved from repository 'C:\10MR_Drivers\'
CategoryInfo          : OperationStopped: (No packages for...\10MR_Drivers\':String) [], RuntimeException
FullyQualifiedErrorId : No packages for computer model '10MR' could be retrieved from repository 'C:\10MR_Drivers\'
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : bei Get-LSUpdate<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\public\Get-LSUpdate.ps1: Zeile 149
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
PipelineIterationInfo : {}

PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.WriteErrorException: 'C:\10MR_Drivers\database.xml' is not a
                        supported URL and does not exist as a filesystem path
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-PackagePathInfo
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : bei Get-PackagePathInfo, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\private\Get-PackagePathInfo.ps1: Zeile 112
                        bei Get-PackagesInRepository, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\private\Get-PackagesInRepository.ps1: Zeile 70
                        bei Get-LSUpdate<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\public\Get-LSUpdate.ps1: Zeile 147
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
PipelineIterationInfo : {0, 1}

PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.WriteErrorException: 'C:\10MR_Drivers\10MR_Win10.xml' is not a
                        supported URL and does not exist as a filesystem path
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-PackagePathInfo
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : bei Get-PackagePathInfo, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\private\Get-PackagePathInfo.ps1: Zeile 112
                        bei Get-PackagesInRepository, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\private\Get-PackagesInRepository.ps1: Zeile 28
                        bei Get-LSUpdate<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\LSUClient\public\Get-LSUpdate.ps1: Zeile 147
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
PipelineIterationInfo : {0, 1}

best regards

**Comment by jantari** [comment]
Hi,

yes it is possible and the information you need should all be here: https://jantari.github.io/LSUClient-docs/docs/topics/self-hosted-repositories/

In short, you either have to use the "Update Retriever" tool to create an offline repository or download/mirror the files from Lenovo and then make sure to edit the paths of the files they point to so they don't refer back to files on the internet that can't be reached from your network

**Comment by horst420** [comment]
thank you
