### ISSUE TITLE
Download error 404

### ISSUE THREAD

**Issue by mtengmo** [jantari/LSUClient#65]
### Version

1.5.0

### Computer Model

82BG

### Problem

$updates = Get-LSUpdate
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.5.0\private\Save-PackageFile.ps1:46 char:9
+         $webClient.DownloadFile($SourceFile.AbsoluteLocation, $Downlo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

WARNING: The command or file '%PACKAGEPATH%\getw10ver7.exe' could not be found from 'C:\Users\mteo\AppData\Local\Temp\f43nujbv.ewv\1toamfcj.d2x' and was not run

**Comment by mtengmo** [comment]
VERBOSE: Detecting install status of package: u3etn09w_w10_x86 (Lenovo USB3.0 LAN Driver for Docks and Adapters - 10 [64])
DEBUG: - |> Node: DetectInstall
DEBUG: - - |> Node: _Driver
DEBUG: - - No installed device matched the driver check
DEBUG: - - < Returning 0 from node _Driver
DEBUG: - Tree was OR: Results: 0
DEBUG: - < Returning 0 from node DetectInstall
VERBOSE: Parsing dependencies for package: u3etn09w_w10_x86 (Lenovo USB3.0 LAN Driver for Docks and Adapters - 10 [64])
DEBUG: - |> Node: Dependencies
DEBUG: - - |> Node: And
DEBUG: - - - |> Node: _OS
DEBUG: - - - < Returning 1 from node _OS
DEBUG: - - - |> Node: _CPUAddressWidth
DEBUG: - - - [ Got: 64, Expected: 64 ]
DEBUG: - - - < Returning 1 from node _CPUAddressWidth
DEBUG: - - - |> Node: Or
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - - |> Node: _PnPID
DEBUG: - - - - < Returning 0 from node _PnPID
DEBUG: - - - Tree was OR: Results: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
DEBUG: - - - < Returning 0 from node Or
DEBUG: - - Tree was AND: Results: 1 1 0
DEBUG: - - < Returning 0 from node And
DEBUG: - Tree was OR: Results: 0
DEBUG: - < Returning 0 from node Dependencies
VERBOSE: Parsing severity override for package: u3etn09w_w10_x86 (Lenovo USB3.0 LAN Driver for Docks and Adapters - 10 [64])
DEBUG: - |> Node: SeverityOverride
DEBUG: - - |> Node: Not
DEBUG: - - Switched state to: DO_NOT_HAVE
DEBUG: - - - |> Node: _Driver
DEBUG: - - - No installed device matched the driver check
DEBUG: - - - < Returning 0 from node _Driver
DEBUG: - - Tree was OR: Results: 0
DEBUG: - - < Returning 1 from node Not
DEBUG: - Tree was OR: Results: 1
DEBUG: - < Returning 1 from node SeverityOverride
DEBUG: Default severity 1 overriden with 2
VERBOSE: Processing package https://download.lenovo.com/marketing/lshm002us_2_.xml
DEBUG: Local package scratch directory: C:\Users\mteo\AppData\Local\Temp\4ivcwmxr.wnd\oh14td10.0oy
VERBOSE: Downloading 'https://download.lenovo.com/marketing/lshm002us_2_.xml' to 'C:\Users\mteo\AppData\Local\Temp\4ivcwmxr.wnd\oh14td10.0oy\lshm002us_2_.xml'
DEBUG: Resolving file path 'lshm002us.exe'
DEBUG: Resolving file path 'lshm002us.txt'
DEBUG: Resolving file path 'getw10ver7.exe'
VERBOSE: Downloading 'https://download.lenovo.com/marketing/getw10ver7.exe' to 'C:\Users\mteo\AppData\Local\Temp\4ivcwmxr.wnd\oh14td10.0oy\getw10ver7.exe'
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.5.0\private\Save-PackageFile.ps1:46 char:9
+         $webClient.DownloadFile($SourceFile.AbsoluteLocation, $Downlo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException


I assume it´s some issue on Lenovo side, but maybe could be some error handling in the script?

**Comment by jantari** [comment]
Looks like it's the same exact URL that's also been reported in #37. I don't think I can fix this on the side of LSUClient because that file is just not available, but it's not a fatal error and if you know (like in this case) that it is not a connectivity problem on your end you can ignore it.
