### ISSUE TITLE
BIOS upgrades - Bitlocker and connected chargers?

### ISSUE THREAD

**Issue by mtengmo** [jantari/LSUClient#68]
### Version

1.5

### Question

How is it working with Bitlocker during BIOS upgrade? I can see that it says suspend in the script?
Similar question about BIOS and connected chargers, is that requirement built-in the EXE file from Lenovo or the script?

**Comment by jantari** [comment]
Currently LSUClient does suspend BitLocker for BIOS updates like you've described, but this could change in the future. If you want to make sure BitLocker is suspended you can do it yourself too, e.g.:

```powershell
[array]$updates = Get-LSUpdate
if ($updates.Type -contains 'BIOS') {
    Get-BitLockerVolume | Suspend-BitLocker
}
```

The requirement for a connected charger on ThinkPads comes from the BIOS setup. You should see an error from the updater tool when no charger is connected. The ExitCode, StandardOutput, StandardError and LogOutput all come directly from the update installer that was run.

**Comment by mtengmo** [comment]
Thanks, it´s even possible to count number of reboots until automatic re-activated: https://learn.microsoft.com/en-us/troubleshoot/windows-client/windows-security/suspend-bitlocker-protection-non-microsoft-updates#suspend-and-resume-bitlocker-protection-by-using-powershell
