### ISSUE TITLE
BIOS - Prompt user to reboot?

### ISSUE THREAD

**Issue by mtengmo** [jantari/LSUClient#69]
### Version

1

### Question

Is it possible to send user a prompt to reboot? A toast notification? 
Or is it usually done in a task sequence ?

Thanks, Magnus

**Comment by jantari** [comment]
Hi, yes you can send toast notifications with PowerShell - some examples:

1. https://den.dev/blog/powershell-windows-notification/ (the link @animentork shared)
2. https://www.imab.dk/windows-10-toast-notification-script/ which looks pretty fancy
3. There's also the BurntToast module https://github.com/Windos/BurntToast which makes it easier

Regarding when to send the notification asking for a reboot, you should follow the advice in the documentation: https://jantari.github.io/LSUClient-docs/docs/topics/bios-and-firmware/#handling-reboots

Going by the `PendingAction` property of an installed update is preferred and recommended over using the `ActionNeeded` registry key and the `-SaveBIOSUpdateInfoToRegistry` switch for the reasons explained in the docs site.

Does this answer your question?

**Comment by jantari** [comment]
Closing due to no response.

It's possible to send prompts and notifications, but it's out of scope for LSUClient. You can add/script them yourself.
