### ISSUE TITLE
Get-LSUpdate => NativeCommandError

### ISSUE THREAD

**Issue by IT360BE** [jantari/LSUClient#79]
### Version

1.5.2

### Computer Model

30E0S1D700

### Problem

VERBOSE: Lenovo Model is: 30E0
cmd.exe : '\\muac\filespace\sds\SCCMSTORE\MDM\Lenovo\Offline-Updater\LSUClient-master'
At \\muac\filespace\sds\SCCMSTORE\MDM\Lenovo\Offline-Updater\LSUClient-master\private\Get-WindowsVersion.ps1:12 char:18
+     $CmdOutput = & "${env:SystemRoot}\System32\cmd.exe" /D /C VER
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('\\muac\filespa...UClient-master':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

**Comment by jantari** [comment]
Thanks, this should be an easy fix just by setting the working directory of cmd to some local path. I hope to have some time later today or tomorrow to look into all your issues

**Comment by jantari** [comment]
LSUClient 1.5.3 just released and includes this fix
