### ISSUE TITLE
Could not download some Updates

### ISSUE THREAD

**Issue by Koob5k** [jantari/LSUClient#81]
### Version

1.5.3

### Computer Model

20T2008NGE

### Problem

...  'https://download.lenovo.com/pccbbs/mobiles/n2yrw10w.exe' to 
'C:\WINDOWS\TEMP\LSUPackages\n2yrw10w\n2yrw10w.exe'
AUSFšHRLICH: Extracting package n2yrw10w ...
AUSFšHRLICH: Installing package n2yrw10w ...
ID             : n2yrw10w
Title: Intel PRO/1000 LAN Adapter Software - 10 (1809 or Later)/11 (21H2 or Later)
Type           : Driver
Success        : True
FailureReason  : 
PendingAction  : REBOOT_SUGGESTED
ExitCode       : 0
StandardOutput : 
StandardError  : 
LogOutput      :Runtime        : 00:00:02.8244436

AUSFšHRLICH: Downloading 'https://download.lenovo.com/pccbbs/mobiles/n2yuj14w.exe' to 
'C:\WINDOWS\TEMP\LSUPackages\n2yuj14w\n2yuj14w.exe'
AUSFšHRLICH: Script failed to carry out one or more actions.
AUSFšHRLICH:Exception "DownloadFile" with 2 Argument(s):  "The connection to the Remote Server could not be established."
AUSFšHRLICH: Script is done running.
Process completed with exit code 1
PowerShell command line returned code 1
啁䙓

### Additional context

The Script has an error when downloading Files for Lenovo X13 Gen 1.

**Comment by Koob5k** [comment]
The error was translated from german.  Maybe the the Error Text is slightly different in English.

**Comment by jantari** [comment]
It looks like you are running into the same issue as #41, please refer to item 2 on this site in the documentation for how to avoid this: https://jantari.github.io/LSUClient-docs/docs/topics/best-practices/

**Comment by jantari** [comment]
Did this solve your problem?

**Comment by Koob5k** [comment]
Yes.
Thank you.
Very useful Module.🖖

jantari ***@***.***> schrieb am So., 26. März 2023, 12:56:

**Comment by jantari** [comment]
Good to hear, and thanks :)
