### ISSUE TITLE
Property cannot be found on this object and no packages for model 21AJ

### ISSUE THREAD

**Issue by HaglerGM** [jantari/LSUClient#82]
### Version

1.5.2

### Computer Model

21AJS6SD00

### Problem

When running the the following commands via a script in a SCCM Task Sequence, we are receiving errors and no updates. However, running these commands outside of the TS, no errors occur. 
$updates = Get-LSUpdate | Where-Object { $_.Installer.Unattended }
$updates | Save-LSUpdate -Verbose
$updates | Install-LSUpdate -Verbose

Error logs attached. Several errors regarding "The property cannot be found on this object at 'LSUCLient\1.5.2\private\Get-PackagePathInfo.p1' 

Additionally receive the error "No packages for computer model '21AJ' could be retrieved from the repository" 
Full error logs from the task sequence attached below. 
[LSUCLient Errors.txt](https://github.com/jantari/LSUClient/files/11019100/LSUCLient.Errors.txt)

**Comment by jantari** [comment]
Some things to try:

1. Are you running this task as SYSTEM, a local user or a domain user? Try a different user
2. If you configure any proxy settings beforehand, either in the task sequence or with a policy, double check they are valid and complete
3. If you run the module from a network share, try running it from a local directory on the machine instead
4. Try running `netsh winsock reset` first - apparently it helped [here](https://github.com/canton7/SyncTrayzor/issues/239)

**Comment by HaglerGM** [comment]
Number 1 seemed to be the issue. I was having problems reaching the powershell module repository during the task sequence, so I changed my script to just copy the LSUClient module from a network drive. Doing so required I change the script to run as a domain admin with file copy permissions instead of SYSTEM, as it was previously. 
The fix for me was to split it into two scripts; one copying the module over and running as a domain admin, the other running the updates as SYSTEM. There may be a more efficient way to do this, but at least it seems to work.

**Comment by jantari** [comment]
Great! I'll close this then.
