### ISSUE TITLE
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (503) Server Unavailable."

### ISSUE THREAD

**Issue by SenderLen** [jantari/LSUClient#85]
### Version

1.5.3

### Computer Model

20W1SCE500

### Problem

$updates = Get-LSUpdate -Verbose 

failed with the below error 

VERBOSE: Processing package https://download.lenovo.com/pccbbs/mobiles/suhotfixww04_2_.xml
VERBOSE: Downloading 'https://download.lenovo.com/pccbbs/mobiles/suhotfixww04_2_.xml' to 'C:\Users\sup\AppData\Local\Temp\r20b2v3f.nsy\qqup1km1.h05\suhotfixww04_2_.xml'
VERBOSE: Downloading 'https://download.lenovo.com/pccbbs/mobiles/win11verify.exe' to 'C:\Users\sup\AppData\Local\Temp\r20b2v3f.nsy\qqup1km1.h05\win11verify.exe'
VERBOSE: Script failed to carry out one or more actions.
VERBOSE: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (503) Server Unavailable."
VERBOSE:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Save-PackageFile(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by jantari** [comment]
If this is happening after a network driver install you are probably running into the same issue as #41 and #81 

In that case please refer to item 2 on this site in the documentation for how to avoid this: https://jantari.github.io/LSUClient-docs/docs/topics/best-practices/

**Comment by SenderLen** [comment]
Thank you for the reply.
In my case the error comes during “ Get-LSUpdate”
 
Could you please look at it once more

**Comment by jantari** [comment]
Ah you're right, although it could've been in a loop iteration after a previous Install-LSUpdate run.

But this is an error from the remote server, not LSUClient. If you can download the file now without an error it could've been a temporary failure of Lenovos servers. If you run a proxy then it can also be returned from that. It's something you have to diagnose on the machine that had the error.

**Comment by SenderLen** [comment]
Thank you for looking at it once again.
 This is the first run and not in a loop. The whole thing fails as it is running in a Try Catch.

I see this failure on all windows 11 machines. Works fine on windows 10 computers.

This error is persistent for some time now, not sure if it’s with Lenovo servers.

What does it means when it says “ Exception calling "DownloadFile" with "2" argument(s):”

**Comment by jantari** [comment]
It means that the function [DownloadFile](https://learn.microsoft.com/dotnet/api/system.net.webclient.downloadfile?view=netframework-4.8) which is used by LSUClient here:

https://github.com/jantari/LSUClient/blob/0a4039120602cf87f5f3a970622f02d35927d447/private/Save-PackageFile.ps1#L46

in `Save-PackageFile` failed with the error/exception which is then printed afterwards.

You should try if you can download the files:

https://download.lenovo.com/pccbbs/mobiles/suhotfixww04_2_.xml
https://download.lenovo.com/pccbbs/mobiles/win11verify.exe

from the same computers as the same user using other methods, like `curl.exe`, a browser, `Invoke-WebRequest` etc. If you can reproduce the error you can diagnose it better.

**Comment by SenderLen** [comment]
Yes, this unsigned file [win11verify.exe] (https://download.lenovo.com/pccbbs/mobiles/win11verify.exe) was being blocked by firewall
