### ISSUE TITLE
n39dd21w - Install issue

### ISSUE THREAD

**Issue by SynMaki** [jantari/LSUClient#89]
### Version

1.5.5

### Computer Model

20W9

### Problem

Driver wants to be installed over and over again but theres no success

We have this issue on all our X13 G2s

ID             : n39dd21w
Title          : Intel Graphics Driver - 10 (19H2 or Later)/11 (21H2 or Later)
Type           : Driver
Success        : False
FailureReason  : INSTALLER_EXITCODE
PendingAction  : NONE
ExitCode       : 1
StandardOutput : {}
StandardError  : {}
LogOutput      : {}
Runtime        : 00:00:01.7362738

Debug Log is attached

### Additional context

[DEBUGLSUClient.txt](https://github.com/jantari/LSUClient/files/11431029/DEBUGLSUClient.txt)

**Comment by jantari** [comment]
Since this is an Intel Graphics driver, there should be a log file from the installer at `$env:ProgramData\Intel\Logs\IntelGFX.log`. Maybe that contains more details on the problem, just an ExitCode of 1 doesn't tell us much unfortunately.

**Comment by SynMaki** [comment]
LOG:
[IntelGFX.log](https://github.com/jantari/LSUClient/files/11474387/IntelGFX.log)

**Comment by lifeunexpected** [comment]
This wont help fix your problem but when i was looking into getting LSUClient into a task sequence someone else had already written the powershell code needed for this and had experienced problems with Intel HD Graphics Driver like the way you are.

So in his powershell script he had added the lines of code below to deal with the "Intel HD Graphics Driver*" problem. He just choose to skip installing the Intel HD Graphics driver.

Specifically this: $updates = Get-LSUpdate | Where-Object { $_.Installer.Unattended -AND $_.Title -notlike "Intel HD Graphics Driver*"}

#No Intel Graphics Driver
#Some weird shit going on with the package here on certain models, making the script run forever
function Run-LSUClientModuleCustom() {
    $regKey = $global:regKey
    if (-NOT(Test-Path -Path $regKey)) { New-Item -Path $regKey -Force | Out-Null }
    $updates = Get-LSUpdate | Where-Object { $_.Installer.Unattended -AND $_.Title -notlike "Intel HD Graphics Driver*"}
    foreach ($update in $updates) {
        Install-LSUpdate $update -Verbose
        New-ItemProperty -Path $regKey -Name $update.ID -Value $update.Title -Force | Out-Null
    }

You can find the information about this from the his website and its a good guide on how it works in a task sequnce.
But for your case, im not sure if this can help you.

https://www.imab.dk/install-lenovo-drivers-and-bios-directly-from-lenovos-driver-catalog-during-osd-using-configuration-manager/

**Comment by jantari** [comment]
Yes, sorry for leaving this up for so long but it didn't look like something LSUClient can fix or work around. Sometimes the packages Lenovo, or their OEMs like Intel, push out are just a little broken unfortunately.

Sskipping them or installing an older version from a [private repository](https://jantari.github.io/LSUClient-docs/docs/topics/self-hosted-repositories/) can be a workaround until an official fix is released.
