### ISSUE TITLE
Additional Intel Management Engine Firmware detected

### ISSUE THREAD

**Issue by Herc08** [jantari/LSUClient#91]
### Version

1.5.5

### Computer Model

20MAS54G00

### Problem

First off, kudos to this thing. I use it in my environment, and it has done wonders.

This is no big deal, but I know you wanted to know if the System Update detects an update, even if LSUClient is supposed to get all available drivers. Looking back at my log, I see `Processing package 'n2crg32w - Intel Management Engine Firmware - 10 (1903 or Later)/11 (21H2 or Later)'` was downloaded and installed. However, once I re-ran System Update, I see it again.

Granted, the LSUClient ran at 9:40 am and the System Client ran at around 12:30 pm. So it is possible Lenovo released an update in the span of two hours. I'm attaching my log file. I use CMTrace formatting since I run this through OSD using MECM. All other updates were installed fine (except the WAN driver, but that's fine). 

Again, no big deal.

### Additional context

![image](https://github.com/jantari/LSUClient/assets/95655456/2aaf2f50-b579-491f-b328-32becbcfa2c0)

[lenovo-driver-update-lsuclient.log](https://github.com/jantari/LSUClient/files/11637375/lenovo-driver-update-lsuclient.log)

**Comment by jantari** [comment]
Thanks for reporting this. Unfortunately without the detailed output from `Get-LSUpdate -Verbose -Debug` I cannot say for certain why the "Intel Management Engine Software Driver" did not get returned by LSUClient, but one possible explanation is this:

The IME Software Driver requires a certain Management Engine Firmware version. Looks like at least `12.0.64.1551`\*. The LSUClient log shows that it installed a Management Engine firmware update during its run - it's possible that the previously installed firmware was too old for the IME Software Driver package to be applicable / installable, but after the LSUClient run that dependency was fixed and thus System Update found it.

This is why I recommend running LSUClient a few times in a loop, see this article in the docs: https://jantari.github.io/LSUClient-docs/docs/topics/best-practices/

---

\*From the IME Software Driver package XML ( https://download.lenovo.com/pccbbs/mobiles/n2nme16w_2_.xml ):

```xml
<Dependencies>
    <And>
        <Or> ... </Or>
        <_Bios> ... </_Bios>
        <_ExternalDetection rc="1,8193">mefwdetect.exe /fw 12.0.64.1551</_ExternalDetection>
        <Or> ... </Or>
    </And>
</Dependencies>
```

**Comment by jantari** [comment]
Have you been able to either reproduce the problem with `Get-LSUpdate -Verbose -Debug` logs or can confirm that it's solved by re-running `Get-LSUpdate` + `Install-LSUpdate` a few times in a row?

**Comment by Herc08** [comment]
No, I was able to reproduce it, unfortunately. You can go ahead and close
this.

**Comment by jantari** [comment]
was or wasn't ? :D just to make sure

**Comment by Herc08** [comment]
Sorry. I was NOT able to reproduce the issue.

**Comment by jantari** [comment]
Okay no worries, if it's not too impractical for you you could always run `Get-LSUpdate` with `-Verbose -Debug` - it's a lot of output, but if you ever run into random or rare issues it makes it possible to diagnose why it happened from the logs. But it is a lot of spammed output if you don't care for it.
