### ISSUE TITLE
Option to force W10 updates

### ISSUE THREAD

**Issue by ghost** [jantari/LSUClient#92]
Due to how Lenovo handles their XML files for obsolete models, W11 XMLs does not contain proper driver/BIOS information. Here is an example of this: https://[download.lenovo.com/catalog/10MR_Win11.xml](https://download.lenovo.com/catalog/10MR_Win11.xml)

Now, if I was instead to use the Windows 10 XML, I would instead get this: https://[download.lenovo.com/catalog/10MR_Win10.xml](https://download.lenovo.com/catalog/10MR_Win10.xml)

As you can see, the Windows 10 XML contains all the driver information needed. Of course driver compatibility can not be guaranteed in this case, but the end user should be aware of this, when applying a switch to force this behavior.

This is of course all due to Lenovo not maintaining XML files for obsolete models, but even though Lenovo discontinued support for them, they might still exist out there.

So my feature request would simple be to add a switch to Get-LSUpdate that enables an admin to force LSUpdate to traverse Windows 10 XML files rather then Windows 11 XML files even though it runs on a Windows 11 OS.

Thank you for your work on this module. It is a tremendous help.

**Comment by jantari** [comment]
Yes, I've noticed this as well when developing the module on Windows 11.

I agree a switch like this would be good, in fact being able to override all of the detected machine characteristics in [CachedHardwareTable](https://github.com/jantari/LSUClient/blob/a68c85fbd721e00576d1f32abd9bdafbdeb31e70/public/Get-LSUpdate.ps1#L134) would be very useful for tests too, so thanks for reminding me :)

This shouldn't be that much work, I just want to find an elegant way to implement it.

**Comment by jantari** [comment]
I pushed an idea of how this could be done to the develop branch if you wanna try it out.

```
Administrator in ~
❯ $10MR_REAL = Get-LSUpdate -Model "10MR" -All -NoTestInstalled -NoTestApplicable -NoTestSeverityOverride

Administrator in ~ took 2s
❯ $10MR_REAL.Count
3

Administrator in ~
❯ $10MR_W10 = Get-LSUpdate -Model "10MR" -All -NoTestInstalled -NoTestApplicable -NoTestSeverityOverride -MachineCharacteristicsOverride @{'_OS' = '10'; '_WindowsBuildVersion' = '19045'}

Administrator in ~ took 3s
❯ $10MR_W10.Count
27
```

By passing a Hashtable to `Get-LSUpdate -MachineCharacteristicsOverride`, any of the info LSUClient collects in [CachedHardwareTable](https://github.com/jantari/LSUClient/blob/a68c85fbd721e00576d1f32abd9bdafbdeb31e70/public/Get-LSUpdate.ps1#L134) can be set to a custom value you choose.

To "spoof" Windows 10 when you are really on 11 you should override both `_OS` and `_WindowsBuildVersion`.

What do you think?

**Comment by EIFOdk** [comment]
Thank you for the update. 

My findings so far is that if you use Get-LSUpdate and pipe that to Install-LSUpdate, it works just fine. However, if you try to use Save-LSUpdate, it throws an error in line 38; [PSCustomOobject]$Package. I think this is because of a typo in the 3 weeks old Save-LSUpdate.ps1 in the Dev branch, that has a parameter named "PSCustomOobject", whereas in the 5 month s old Save-LSUpdate.ps1 in the Master branch it is named "pscustomobject" (without the extra 'O').

Reason we use Save-LSUpdate, is that we run BIOS updates with custom parameters to add a logo file.

**Comment by EIFOdk** [comment]
Thank you for pointing the internal detection out. I will keep that in mind. I would not expect 100% compatibility with a solution like this anyway. But it's a nice option to have for a possible workaround for obsolete model, so this change will be very welcome. I'll be looking forward to this being in the master branch.

Thanks again!
