### ISSUE TITLE
Installation / Download from specific Packages not working

### ISSUE THREAD

**Issue by new-it** [jantari/LSUClient#93]
### Version

1.5.5

### Computer Model

20YQS0NF00

### Problem

We want to create a driver baseline with specific packages which should be installed. So not everytime the newest one, only when it was tested internally.

We tried these:

PS C:\WINDOWS\system32> Get-LSUpdate

ID       Title                       Type ReleaseDate         Version   Severity
--       -----                       ---- -----------         -------   --------
n37uj14w BIOS Update Utility - 10/11 BIOS 26.07.2023 00:00:00 1.26.1.11 Recommended

PS C:\WINDOWS\system32> Install-LSUpdate -Package n37uj14w
Save-PackageFile : Das Argument kann nicht an den Parameter "SourceFile" gebunden werden, da es NULL ist.
In C:\Program Files\WindowsPowerShell\Modules\LSUClient\1.5.5\public\Install-LSUpdate.ps1:68 Zeichen:42
+             $FullPath = Save-PackageFile @SpfParams
+                                          ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Save-PackageFile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Save-PackageFile

Install-LSUpdate : The installer of package '' could not be accessed or found and will be skipped
In Zeile:1 Zeichen:1
+ Install-LSUpdate -Package 'n37uj14w'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-LSUpdate

**Comment by jantari** [comment]
Please check the examples in the documentation: https://jantari.github.io/LSUClient-docs/docs/topics/examples/

The `Install-LSUpdate -Package` parameter takes a `[Lenovo Package]` object as returned by `Get-LSUpdate`.

```powershell
Get-LSUpdate | Where ID -eq 'n37uj14w' | Install-LSUpdate
```

That being said I think to achieve what you want you need a private packages repository: https://jantari.github.io/LSUClient-docs/docs/topics/self-hosted-repositories/

Because Lenovo doesn't keep old / superseded packages around in their official repo.

**Comment by jantari** [comment]
Did that work for you?

**Comment by new-it** [comment]
We probably won't go through the hassle of creating a package repo on our own, but thanks for the insight!
