### ISSUE TITLE
Updates not found for Thinkpad E14 Gen5

### ISSUE THREAD

**Issue by riverboatmuffin** [jantari/LSUClient#98]
### Version

1.6.0

### Computer Model

21JK005AGE

### Problem

When running "Get-LSUpdate" i only get one drive as respond:
ID       Title                       Type ReleaseDate         Version Severity   
--       -----                       ---- -----------         ------- --------   
r2auj50w BIOS Update Utility - 10/11 BIOS 27.09.2023 00:00:00 1.25    Recommended

but device is missing lot of drivers like Wifi-Card, Touchpad and so on.

on the lenovo driver website are all drivers ready to download: https://pcsupport.lenovo.com/at/de/products/laptops-and-netbooks/thinkpad-edge-laptops/thinkpad-e14-gen-5-type-21jk-21jl/21jk/21jk005age/pf4k8n8f/downloads/driver-list

### Additional context

<img width="722" alt="screen1" src="https://github.com/jantari/LSUClient/assets/101648396/2a71e757-ec9f-4711-af91-c5532613b707">
<img width="495" alt="screen2" src="https://github.com/jantari/LSUClient/assets/101648396/63bc910c-e741-434e-9bf5-315df14ad3ee">

**Comment by jantari** [comment]
Please run `Get-LSUpdate -Verbose -Debug` to get the full detailed output of what is happening and share that.

**Comment by riverboatmuffin** [comment]
Hi,
i don't know what happend. But today it found all drivers - so the issue can be closed.

thank you!

**Comment by riverboatmuffin** [comment]
Hi,

sorry second E14 Gen5 has the same problem.
Here is the debug log: 
[lsuclient-log.txt](https://github.com/jantari/LSUClient/files/13248991/lsuclient-log.txt)

**Comment by jantari** [comment]
A lot of the packages being evaluated on this machine did not have their dependencies satfisfied (Log entries: `Returning 0 from node Dependencies`). This will result in the packages being considered inapplicable to your machine (`IsApplicable` set to False by LSUClient).

A repeating problem I can see in the log is that most packages fail their _WindowsBuildVersion dependency test:

```
DEBUG: - - - - |> Node: And
DEBUG: - - - - - |> Node: _OS
DEBUG: - - - - - < Returning 1 from node _OS
DEBUG: - - - - - |> Node: _CPUAddressWidth
DEBUG: - - - - - [ Got: 64, Expected: 64 ]
DEBUG: - - - - - < Returning 1 from node _CPUAddressWidth
DEBUG: - - - - - |> Node: _WindowsBuildVersion
DEBUG: - - - - - [ Got: 19044, Expected: 19045^ ]
DEBUG: - - - - - < Returning 0 from node _WindowsBuildVersion
DEBUG: - - - - Tree was AND: Results: 1 1 0
```

from the test output `Got: 19044, Expected: 19045^` it looks like you are running Windows 10 Version 21H2, **which is end of life!**

https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro
https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-21h2-end-of-servicing

all of these packages expect/require at least Windows 10 22H2 (Windows build version 10.0.19045 and up) to pass their dependency checks and be applicable.

Technically you can probably still install these (after getting them with `Get-LSUpdate -All`) and LSUClient also provides a way for advanced users to override the machine information to "spoof" a different Windows version, but really you should just update to a supported version of Windows.

**Comment by riverboatmuffin** [comment]
Thanks jantari that was the issue.
