### ISSUE TITLE
Exception setting "_CPUAddressWidth":

### ISSUE THREAD

**Issue by IT360BE** [jantari/LSUClient#99]
### Version

1.6

### Computer Model

20S7S02200

### Problem

Import-Module .\LSUClient.psm1
$model = "20S7S02200"
Get-LSUpdate -Model $model -All

Throws this : 
Exception setting "_CPUAddressWidth": "Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.UInt16"."
At \\******\SCCMSTORE\MDM\Lenovo\Offline-Updater\LSUClient-master-1.60\LSUClient.psm1:353 char:13
+             $this._CPUAddressWidth = [wmisearcher]::new('SELECT Addre ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 
WARNING: The repository 'https://download.lenovo.com/catalog' did not contain either a '20S7_Win10.xml' or 'database.xml' file to get packages from
No packages for computer model '20S7' could be retrieved from repository 'https://download.lenovo.com/catalog'
At \\*********\SCCMSTORE\MDM\Lenovo\Offline-Updater\LSUClient-master-1.60\public\Get-LSUpdate.ps1:159 char:13
+             throw "No packages for computer model '${Model}' could be ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No packages for...vo.com/catalog':String) [], RuntimeException
    + FullyQualifiedErrorId : No packages for computer model '20S7' could be retrieved from repository 'https://download.lenovo.com/catalog'

**Comment by jantari** [comment]
The `_CPUAddressWidth` error is fixed, and the `No packages for computer model ...` error is easier to troubleshoot in LSUClient 1.6.1 now

**Comment by jantari** [comment]
oops I just realized my fix didn't actually work as expected and this error still happens

**Comment by jantari** [comment]
Version 1.6.2 is out now and includes this fix (for real this time) :smile:
